import type { BundleDetail, FAQ } from "./types";

export const bundleFAQs: FAQ[] = [
  {
    question: "What is LeadGuruTeach?",
    answer:
      "LeadGuruTeach is an educational platform where you learn the latest skills and advancements happening in the professional realm, combined with a powerful affiliate program.",
  },
  {
    question: "What is the LeadGuruTeach Affiliate program?",
    answer:
      "LeadGuruTeach provides you the opportunity to earn money online by selling its courses. It's a great opportunity for people who want to start affiliate marketing or earn money online.",
  },
  {
    question: "How much commission does LeadGuruTeach offer?",
    answer: "LeadGuruTeach provides up to 87% commission on every referral.",
  },
  {
    question: "How is LeadGuruTeach different from other courses and affiliate programs?",
    answer:
      "LeadGuruTeach offers up to 87% commission on each referral, follows a Same Day Payout policy, and provides quality content for organic social media marketing.",
  },
  {
    question: "What benefits do I get if I buy the product?",
    answer:
      "LeadGuruTeach offers revolutionary online courses that improve your skills, plus a special affiliate link to earn commission from every purchase made through your referral.",
  },
  {
    question: "When will I get my commission?",
    answer:
      "You will receive payment at night for the total commission for sales generated before 5:00 PM throughout the day.",
  },
  {
    question: "Can I upgrade my plans?",
    answer: "Yes, you can upgrade your plan at any time.",
  },
];

export const certificateSteps = [
  "View Course — Explore engaging course content designed to enhance your skills.",
  "Learn — Absorb valuable insights and industry best practices from expert trainers.",
  "Attend Test — Assess your understanding with a thoughtfully crafted test.",
  "Get Certificate — Receive your Certificate of Completion upon successful completion.",
];

export const bundleDetails: BundleDetail[] = [
  {
    id: "bronze",
    slug: "bronze-bundle",
    name: "Bronze Bundle",
    tagline: "Office Skills That Set You Apart!",
    price: 1899,
    originalPrice: 2500,
    courses: 4,
    hours: 21,
    enrollments: "140K+",
    lectures: 81,
    features: ["Live Q&A Support", "140K+ Students Enrolled", "LeadGuruTeach Certificate"],
    gradient: "from-amber-600/20 to-orange-600/20",
    description:
      "The Bronze Bundle is designed to make you efficient, professional, and job-ready by mastering essential office skills. Whether you're a student, preparing for a job, or already working, these courses will help you work smarter, communicate effectively, and confidently present your ideas.",
    specialization: [
      "Microsoft Office Proficiency — Learn MS Word, Excel, and PowerPoint for professional documentation, data analysis, and impactful presentations.",
      "Professional Communication — Write professional emails, craft clear messages, and express ideas effectively in meetings and reports.",
      "Resume & Interview Preparation — Structure your resume, prepare strong interview answers, and present yourself confidently.",
    ],
    journeyPoints: [
      {
        title: "Work Efficiency & Organization",
        description:
          "Use essential MS Office tools to organize work, manage data, and create well-structured reports and presentations.",
      },
      {
        title: "Confident Workplace Communication",
        description:
          "Write professional emails, prepare structured documents, and confidently communicate ideas in meetings.",
      },
      {
        title: "Interview Readiness",
        description:
          "Ace job interviews by answering questions effectively and leaving a strong impression on recruiters.",
      },
      {
        title: "Effective Presentation Skills",
        description:
          "Design visually appealing PowerPoint presentations that captivate your audience.",
      },
      {
        title: "Smarter Problem-Solving",
        description:
          "Use Excel formulas and structured data management to make everyday work easier and more efficient.",
      },
    ],
    bundleCourses: [
      { title: "MS Word Course", description: "Document creation, editing, and professional formatting." },
      { title: "MS Excel Course", description: "Data analysis, visualization, and spreadsheet functions." },
      { title: "MS PowerPoint Course", description: "Engaging and impactful presentation design." },
      { title: "How To Crack Interview With Ease", description: "Techniques to prepare for and excel in job interviews." },
    ],
    includes: [
      "21 hours on-demand video",
      "Full lifetime access",
      "Access on mobile and PC",
      "Assignments",
      "Certificate of Completion",
    ],
    certificateSteps,
  },
  {
    id: "silver",
    slug: "silver-package",
    name: "Silver Package",
    tagline: "Build Your Digital Presence & Communication Skills!",
    price: 3499,
    originalPrice: 3999,
    courses: 14,
    hours: 52,
    enrollments: "90K+",
    lectures: 210,
    features: ["Live Q&A Support", "90K+ Students Enrolled", "LeadGuruTeach Certificate"],
    gradient: "from-slate-400/20 to-slate-600/20",
    description:
      "The Silver Package equips you with essential digital and communication skills to stand out in today's competitive job market. From social media marketing basics to professional English fluency, this bundle covers the fundamentals every modern professional needs.",
    specialization: [
      "Digital Marketing Basics — Understand SEO, social media marketing, and content creation fundamentals.",
      "Communication Excellence — Master spoken and written English for professional settings.",
      "Personal Branding — Build your online presence and network effectively on LinkedIn and beyond.",
    ],
    journeyPoints: [
      {
        title: "Digital Literacy",
        description: "Gain foundational knowledge of digital tools and online marketing channels.",
      },
      {
        title: "Professional Communication",
        description: "Improve your English fluency and public speaking for workplace success.",
      },
      {
        title: "Social Media Skills",
        description: "Learn to create engaging content and grow your personal brand online.",
      },
      {
        title: "Career Foundation",
        description: "Build a strong resume, LinkedIn profile, and interview skills.",
      },
    ],
    bundleCourses: [
      { title: "Digital Marketing Fundamentals" },
      { title: "Social Media Marketing" },
      { title: "English Fluency for Professionals" },
      { title: "Public Speaking Basics" },
      { title: "LinkedIn Profile Optimization" },
      { title: "Content Writing Essentials" },
      { title: "Email Marketing Basics" },
      { title: "Personal Branding 101" },
      { title: "Resume & Cover Letter Mastery" },
      { title: "Interview Skills Advanced" },
      { title: "Time Management & Productivity" },
      { title: "Freelancing Starter Guide" },
      { title: "Canva for Beginners" },
      { title: "Basic Video Editing" },
    ],
    includes: [
      "52 hours on-demand video",
      "Full lifetime access",
      "Access on mobile and PC",
      "Assignments & quizzes",
      "Certificate of Completion",
    ],
    certificateSteps,
  },
  {
    id: "gold",
    slug: "gold-package",
    name: "Gold Package",
    tagline: "Master In-Demand Skills & Start Earning!",
    price: 6999,
    originalPrice: 7999,
    courses: 23,
    hours: 70,
    enrollments: "70K+",
    lectures: 340,
    features: ["Live Q&A Support", "70K+ Students Enrolled", "LeadGuruTeach Certificate"],
    gradient: "from-yellow-500/20 to-amber-600/20",
    popular: true,
    description:
      "The Gold Package is our most popular bundle, combining advanced digital marketing, sales, and personal development courses. Designed for ambitious professionals who want to master high-income skills and start earning through freelancing or affiliate marketing.",
    specialization: [
      "Advanced Digital Marketing — Facebook Ads, Google Ads, SEO, and email marketing mastery.",
      "Sales & Business Development — Learn proven sales techniques and business growth strategies.",
      "Affiliate Marketing — Start earning commissions by promoting courses and products online.",
    ],
    journeyPoints: [
      {
        title: "High-Income Skill Mastery",
        description: "Learn the most in-demand skills that employers and clients are actively seeking.",
      },
      {
        title: "Start Earning Online",
        description: "Launch your affiliate marketing journey and start generating passive income.",
      },
      {
        title: "Business Acumen",
        description: "Understand business strategy, sales funnels, and customer psychology.",
      },
      {
        title: "Personal Growth",
        description: "Develop emotional intelligence, leadership, and mindset for long-term success.",
      },
    ],
    bundleCourses: [
      { title: "Facebook Ads Mastery" },
      { title: "Google Ads Complete Course" },
      { title: "SEO & Content Marketing" },
      { title: "Email Marketing Advanced" },
      { title: "Sales Funnel Building" },
      { title: "Affiliate Marketing Pro" },
      { title: "Copywriting for Conversions" },
      { title: "Instagram Growth Strategy" },
      { title: "YouTube Channel Growth" },
      { title: "WhatsApp Marketing" },
      { title: "Lead Generation Mastery" },
      { title: "Business Strategy Fundamentals" },
      { title: "Emotional Intelligence at Work" },
      { title: "Leadership & Team Management" },
      { title: "Stock Market Basics" },
      { title: "Freelancing on Upwork & Fiverr" },
      { title: "Advanced Public Speaking" },
      { title: "Storytelling for Business" },
      { title: "LinkedIn Lead Generation" },
      { title: "Video Marketing Strategy" },
      { title: "Personal Finance Management" },
      { title: "Mind Power & Productivity" },
      { title: "Negotiation Skills" },
    ],
    includes: [
      "70 hours on-demand video",
      "Full lifetime access",
      "Access on mobile and PC",
      "Live Q&A sessions",
      "Assignments & projects",
      "Certificate of Completion",
    ],
    certificateSteps,
  },
  {
    id: "platinum",
    slug: "platinum-package",
    name: "Platinum Package",
    tagline: "Become an Industry Expert & Thought Leader!",
    price: 12999,
    originalPrice: 13999,
    courses: 25,
    hours: 83,
    enrollments: "50K+",
    lectures: 420,
    features: ["Live Q&A Support", "50K+ Students Enrolled", "LeadGuruTeach Certificate"],
    gradient: "from-cyan-400/20 to-blue-500/20",
    description:
      "The Platinum Package is designed for professionals ready to become industry experts. With advanced courses in digital marketing, coaching, content creation, and business strategy, you'll gain the expertise to command premium rates and build a thriving personal brand.",
    specialization: [
      "Expert-Level Marketing — Advanced Facebook Ads, funnel optimization, and conversion rate mastery.",
      "Coaching & Mentoring Skills — Learn to coach others and build your own training business.",
      "Content Creation Mastery — Professional video editing, graphic design, and content strategy.",
    ],
    journeyPoints: [
      {
        title: "Industry Expertise",
        description: "Develop deep knowledge in your chosen field and become a recognized authority.",
      },
      {
        title: "Premium Client Acquisition",
        description: "Learn strategies to attract and retain high-paying clients and customers.",
      },
      {
        title: "Build Your Training Business",
        description: "Create and sell your own courses, workshops, and coaching programs.",
      },
      {
        title: "Advanced Personal Branding",
        description: "Establish yourself as a thought leader across multiple platforms.",
      },
    ],
    bundleCourses: [
      { title: "Advanced Facebook Ads & Scaling" },
      { title: "Funnel Optimization Mastery" },
      { title: "High-Ticket Sales Strategy" },
      { title: "Life Coaching Certification" },
      { title: "NLP for Professionals" },
      { title: "Professional Video Editing" },
      { title: "Advanced Graphic Design" },
      { title: "Podcast Creation & Growth" },
      { title: "Webinar Marketing Mastery" },
      { title: "Corporate Training Skills" },
      { title: "Advanced LinkedIn Strategy" },
      { title: "Influencer Marketing" },
      { title: "E-commerce Business Setup" },
      { title: "Advanced Stock Market Trading" },
      { title: "Mind & Life Coaching" },
      { title: "Youth Transformation Coaching" },
      { title: "Corporate Communication" },
      { title: "Advanced Copywriting" },
      { title: "Brand Strategy & Positioning" },
      { title: "CRM & Automation Tools" },
      { title: "Advanced Affiliate Strategies" },
      { title: "Public Relations Basics" },
      { title: "Event Marketing" },
      { title: "Advanced SEO & Analytics" },
      { title: "Business Scaling Framework" },
    ],
    includes: [
      "83 hours on-demand video",
      "Full lifetime access",
      "Access on mobile and PC",
      "Priority live Q&A support",
      "1-on-1 mentorship session",
      "Certificate of Completion",
    ],
    certificateSteps,
  },
  {
    id: "diamond",
    slug: "diamond-package",
    name: "Diamond Package",
    tagline: "Elite Training for Top Performers!",
    price: 19999,
    originalPrice: 29999,
    courses: 28,
    hours: 96,
    enrollments: "20K+",
    lectures: 510,
    features: ["Live Q&A Support", "20K+ Students Enrolled", "LeadGuruTeach Certificate"],
    gradient: "from-purple-500/20 to-indigo-600/20",
    description:
      "The Diamond Package is our elite offering for top performers who demand the best. With comprehensive training across digital marketing, coaching, finance, and entrepreneurship, this bundle transforms you into a multi-skilled professional ready to dominate any industry.",
    specialization: [
      "Complete Digital Empire — Master every digital marketing channel and automation tool.",
      "Executive Coaching Skills — Advanced coaching, NLP, and transformational leadership training.",
      "Wealth Building — Stock market, crypto basics, passive income, and business investment strategies.",
    ],
    journeyPoints: [
      {
        title: "Multi-Skill Mastery",
        description: "Become proficient across marketing, sales, coaching, and content creation simultaneously.",
      },
      {
        title: "Build Multiple Income Streams",
        description: "Create affiliate income, freelancing revenue, and passive income sources.",
      },
      {
        title: "Leadership Excellence",
        description: "Develop the mindset and skills to lead teams and build organizations.",
      },
      {
        title: "Financial Freedom Path",
        description: "Learn investment, wealth management, and business scaling for long-term prosperity.",
      },
    ],
    bundleCourses: [
      { title: "Complete Digital Marketing Suite" },
      { title: "Advanced Coaching Certification" },
      { title: "NLP Master Practitioner" },
      { title: "Stock Market Advanced Trading" },
      { title: "Crypto & Web3 Basics" },
      { title: "Passive Income Blueprint" },
      { title: "Agency Building Masterclass" },
      { title: "Advanced Video Production" },
      { title: "AI Tools for Business" },
      { title: "Advanced Sales Psychology" },
      { title: "Executive Presence Training" },
      { title: "Team Building & HR Basics" },
      { title: "Franchise & Business Models" },
      { title: "International Marketing" },
      { title: "Advanced Personal Branding" },
      { title: "Mental Wellness for Leaders" },
      { title: "Advanced Public Relations" },
      { title: "Real Estate Investment Basics" },
      { title: "Tax Planning for Entrepreneurs" },
      { title: "Advanced Affiliate Empire" },
      { title: "Course Creation Masterclass" },
      { title: "Community Building Strategy" },
      { title: "Advanced Analytics & Data" },
      { title: "Crisis Management" },
      { title: "Global Business Expansion" },
      { title: "Advanced Negotiation & Deals" },
      { title: "Legacy Building Framework" },
      { title: "Masterclass: Success Mindset" },
    ],
    includes: [
      "96 hours on-demand video",
      "Full lifetime access",
      "Access on mobile and PC",
      "VIP live Q&A support",
      "3x 1-on-1 mentorship sessions",
      "Exclusive community access",
      "Certificate of Completion",
    ],
    certificateSteps,
  },
  {
    id: "startup",
    slug: "startup-package",
    name: "Startup Package",
    tagline: "Launch Your Business & Scale to Success!",
    price: 29999,
    originalPrice: 49999,
    courses: 32,
    hours: 100,
    enrollments: "20K+",
    lectures: 580,
    features: ["Live Q&A Support", "20K+ Students Enrolled", "LeadGuruTeach Certificate"],
    gradient: "from-emerald-500/20 to-teal-600/20",
    description:
      "The Startup Package is the ultimate all-in-one solution for aspiring entrepreneurs. From ideation to scaling, this comprehensive bundle covers every aspect of building and growing a successful business in the digital age, plus the affiliate skills to fund your journey.",
    specialization: [
      "Entrepreneurship Fundamentals — Business planning, legal setup, funding, and go-to-market strategy.",
      "Full-Stack Digital Marketing — Every channel, tool, and tactic to grow your startup online.",
      "Revenue & Growth Systems — Sales, affiliate marketing, automation, and scaling frameworks.",
    ],
    journeyPoints: [
      {
        title: "Launch Your Startup",
        description: "Validate your idea, build an MVP, and launch your business with confidence.",
      },
      {
        title: "Fund Your Growth",
        description: "Use affiliate marketing and freelancing income to bootstrap your startup.",
      },
      {
        title: "Scale Rapidly",
        description: "Implement proven growth systems, hire teams, and expand to new markets.",
      },
      {
        title: "Build Lasting Wealth",
        description: "Create multiple revenue streams and investment portfolios for financial freedom.",
      },
    ],
    bundleCourses: [
      { title: "Startup Ideation & Validation" },
      { title: "Business Plan Writing" },
      { title: "Legal & Compliance for Startups" },
      { title: "Fundraising & Investor Pitching" },
      { title: "Complete Digital Marketing" },
      { title: "Growth Hacking Strategies" },
      { title: "Product Development Basics" },
      { title: "UX/UI Design Fundamentals" },
      { title: "No-Code App Building" },
      { title: "E-commerce Launch Guide" },
      { title: "SaaS Business Model" },
      { title: "Content Marketing at Scale" },
      { title: "Influencer Partnership Strategy" },
      { title: "Advanced Affiliate Marketing" },
      { title: "Sales Team Building" },
      { title: "Customer Success Framework" },
      { title: "Financial Modeling for Startups" },
      { title: "HR & Team Culture" },
      { title: "Remote Team Management" },
      { title: "International Expansion" },
      { title: "PR & Media Strategy" },
      { title: "Advanced Coaching for Founders" },
      { title: "Mindset for Entrepreneurs" },
      { title: "Automation & AI for Startups" },
      { title: "Community-Led Growth" },
      { title: "Subscription Business Models" },
      { title: "Exit Strategy Planning" },
      { title: "Personal Brand for Founders" },
      { title: "Networking & Partnerships" },
      { title: "Crisis & Pivot Management" },
      { title: "Wealth Management for Founders" },
      { title: "Legacy & Impact Building" },
    ],
    includes: [
      "100 hours on-demand video",
      "Full lifetime access",
      "Access on mobile and PC",
      "VIP live Q&A support",
      "5x 1-on-1 mentorship sessions",
      "Exclusive founder community",
      "Startup toolkit & templates",
      "Certificate of Completion",
    ],
    certificateSteps,
  },
];

export function getBundleBySlug(slug: string): BundleDetail | undefined {
  return bundleDetails.find((b) => b.slug === slug || b.id === slug);
}

export function getAllBundleSlugs(): string[] {
  return bundleDetails.map((b) => b.slug);
}
